apiVersion: v2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.27.0
description: A library chart for common resources
maintainers:
  - email: cwr@teuto.net
    name: cwrau
  - email: mw@teuto.net
    name: marvinWolff
  - email: st@teuto.net
    name: tasches
name: common
sources:
  - https://github.com/teutonet/teutonet-helm-charts/tree/common-v1.4.0/charts/common
  - https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/common
type: library
version: 1.4.0
