roles:
  - name: pizza
    ensure: present
    login: false
    superuser: false
databases:
  kuchen:
    owner: pizza
    extensions:
      - name: hstore
        version: "1.8"
        schema: "public"
    schemas:
      - name: torte
        owner: pizza
