roles:
  - name: kruemel
    ensure: present
    login: false
    superuser: false
databases:
  kuchen:
    owner: pizza
    extensions:
      pgaudit: {}
  torte:
    owner: keks
    extensions:
      pgvector: {}
