{{- if ((.Values.backup.provider).velero).backupStorageLocations }}
{{- $providerMap := dict "minio" "accessKeyID" -}}
{{- range $name, $spec := .Values.backup.backupStorageLocations -}}
  {{- $providerName := include "base-cluster.backup.velero.getProviderName" $spec.provider -}}
  {{- if dig $providerName (get $providerMap $providerName | required (printf "Credentials for provider '%s' not implemented" $providerName)) false $spec.provider }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-velero-backuplocation-%s" (include "common.names.fullname" $) $name }}
  namespace: backup
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
    app.kubernetes.io/part-of: backup
stringData:
  {{ $providerName }}: |-{{- include "base-cluster.backup.velero.credential" $spec.provider | nindent 4 }}
  {{- end -}}
{{- end }}
{{- end }}
