databaseImage:
  registry: ghcr.io
  repository: cloudnative-pg/postgresql
  tag: "18.2@sha256:7e95094990c3fd8150adcdc5888c02eeffb451427eca580a8692a3a4500deae9"
instances: 3
logLevel: info
storageSize: 1Gi
podMonitorLabels:
  managed.by/monitoring: teutonet
