databaseImage:
  registry: ghcr.io
  repository: cloudnative-pg/postgresql
  tag: "16.12@sha256:7fe820e900df4492243a1d4aeff88e1eb2b9706ac30bb1f10565e4a71099023f"
instances: 3
logLevel: info
storageSize: 1Gi
podMonitorLabels:
  managed.by/monitoring: teutonet
