{{- $name := "ckan" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  name: {{ printf "%s-%s" (include "common.names.fullname" $) $name | quote }}
spec:
  accessModes:
    - {{ .Values.ckan.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.ckan.persistence.size }}
  {{ include "common.storage.class" (dict "persistence" .Values.ckan.persistence "global" $ )}}