apiVersion: v2
name: teuto-portal-k8s-worker
description: A Helm chart for deploying the portal worker application to k8s
type: application
version: 3.4.3
appVersion: 2.0.0
maintainers:
  - name: cwrau
    email: cwr@teuto.net
  - name: marvinWolff
    email: mw@teuto.net
  - name: tasches
    email: st@teuto.net
dependencies:
  - name: common
    version: 1.8.0
    repository: oci://ghcr.io/teutonet/teutonet-helm-charts
sources:
  - https://github.com/teutonet/teutonet-helm-charts/tree/teuto-portal-k8s-worker-v3.4.2/charts/teuto-portal-k8s-worker
  - https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/teuto-portal-k8s-worker
annotations:
  artifacthub.io/images: |-
    - image: registry-gitlab.teuto.net/4teuto/dev/teuto-portal/teuto-portal-k8s-worker/teuto-portal-k8s-worker:4.2.0@sha256:7818679d3ff38b4afb54f0ea3062aa3128a2568beade1fc9062b2f96cd2c982e  #  default/Deployment/teuto-portal-k8s-worker.yaml
