name: Release Charts

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - charts/*/Chart.yaml

jobs:
  getChangedCharts:
    if: ${{ contains(github.event.head_commit.message, '[bot] release') || github.event.name != 'push' }}
    uses: ./.github/workflows/get-changed-charts.yaml
  release:
    if: ${{ contains(github.event.head_commit.message, '[bot] release') || github.event.name != 'push' }}
    runs-on: ubuntu-latest
    needs: getChangedCharts
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Extract and add helm repos and single out the changed chart
        id: helm-repos
        env:
          CHARTS: ${{ needs.getChangedCharts.outputs.charts }}
        run: |
          set -ex
          set -o pipefail
          mkdir changed_charts
          for CHART in $(jq -r '. | values[]' <"$CHARTS"); do
            CHART_DIR="charts/${CHART}"
            FILE="${CHART_DIR}/Chart.yaml"
            yq e '.dependencies.[].repository' "$FILE" | sort -u | awk '{print NR " " $1}' | xargs -r -n 2 helm repo add
            mv "${CHART_DIR}" changed_charts/
            rm -rf charts
          done
          mv changed_charts charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.ACTIONS_BOT_TOKEN }}"
