name: Sync CODEOWNERS and Docs

on:
  push:
    branches:
      - main
    paths:
      - charts/*/README.md.gotmpl
      - charts/*/README.md
      - charts/*/values.schema.json
      - charts/*/Chart.yaml
      - .github/scripts/sync-codeowners.sh
      - .github/workflows/sync-codeowners-and-docs.yaml
      - .github/CODEOWNERS
      - .github/json-schema-to-md.yaml

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/setup-python@v4
      - run: pip install json-schema-for-humans

      - run: sudo snap install yq
      - name: generate CODEOWNERS
        run: |
          ./.github/scripts/sync-codeowners.sh > .github/CODEOWNERS

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update 'CODEOWNERS'"
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com

      - name: generate values.md
        run: |
          for chart in charts/*; do
            [[ "$chart" = "charts/*" ]] && continue
            generate-schema-doc --config-file .github/json-schema-to-md.yaml "$chart/values.schema.json" "$chart/values.md"
          done
      - name: generate Docs
        uses: docker://jnorwood/helm-docs:latest

      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update 'README.md's"
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com

